package com.ejpm.euler.problem.impl;

import com.ejpm.euler.problem.Problem;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not exceed
 * four million.
 *
 * @author edgar.mateus
 */
public class Problem2 implements Problem {

    @Override
    public void execute() {

        long soma = 0;
        int count = 0;

        do {
            long a = fibonnaci(count);
            if (a % 2 == 0) {
                soma += fibonnaci(count);
            }

            count++;
        } while (fibonnaci(count) < 4000000);

        System.out.println("Problem 2:\t The sum of all the even-valued terms in fibo sequence which do not exceed "
                + " four million is " + soma);
    }

    private static long fibonnaci(long mes) {
        if (mes == 0) {
            return 0;
        } else if (mes == 1) {
            return 1;
        } else {
            return fibonnaci(mes - 1) + fibonnaci(mes - 2);
        }
    }

}
